#ifndef QCP_LIB_CONFIG_H
#define QCP_LIB_CONFIG_H

#define QCP_LIB_VERSION "2.1.0"
#define QCP_LIB_VERSION_MAJOR "2"
#define QCP_LIB_VERSION_MINOR "1"
#define QCP_LIB_VERSION_PATCH "0"

#endif // QCP_LIB_CONFIG_H
